baseURL = 'https://omid.dev/'
title = 'Omid Farhang'
theme = 'PaperMod'

copyright = 'All rights reserved.'
defaultContentLanguage = 'en'

# disqusShortname = 'omidnetwork'
googleAnalytics = 'G-EFXLS4ZNG6'

show_reading_time = true

[menu]
[[menu.main]]
  identifier = 'blog'
  name = 'Posts'
  url = '/posts'
  weight = 1
[[menu.main]]
  identifier = 'aboutMe'
  name = 'About me'
  url = '/about-me'
  weight = 1
[[menu.main]]
  identifier = 'contactMe'
  name = 'Contact me'
  url = '/contact-me'
  weight = 1
[[menu.main]]
  identifier = 'services'
  name = 'Services'
  url = '/services'
  weight = 1


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

[languages]
  [languages.en]
    title = 'Omid Farhang'
    languageName = 'English'
    languageCode = 'en-US'
    weight = 1
  [languages.fa]
    title = 'امید فرهنگ'
    languageName = 'فارسی'
    languageCode = 'fa-IR'
    weight = 2
    languagedirection = 'rtl'
  [languages.de]
    title = 'Omid Farhang'
    languageName = 'Deutsch'
    languageCode = 'de-DE'
    weight = 2
[params]
  linkedin = 'https://linkedin.com/in/omidfarhang'
  twitter = 'https://twitter.com/omidfarhangen'
  github = 'https://github.com/omidfarhang'
  mastodon = 'https://floss.social/@omid'
  instagram = 'https://instagram.com/omidfarhang'
  telegram = 'https://t.me/omidfarhang'
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableScrollToTop = false
  showtoc = true
  tocopen = false
  [params.navigation]
  help = 'Help'
  [params.assets]
  favicon = "/logo/favicon.ico"
  favicon16x16 = "/logo/favicon-16x16.png"
  favicon32x32 = "/logo/favicon-32x32.png"
  apple_touch_icon = "/logo/apple-touch-icon.png"
  safari_pinned_tab = "/logo/safari-pinned-tab.svg"
[outputs]
  home = [ "HTML", "RSS", "JSON" ]