baseURL: 'https://omid.dev/'
title: Omid Farhang
theme: PaperMod
copyright: '© 2024 Omid Farhang | All rights reserved.'
defaultContentLanguage: en
googleAnalytics: G-EFXLS4ZNG6
show_reading_time: true

# disqusShortname: omidnetwork

menu:
  main:
    - identifier: blog
      name: Posts
      url: /posts
      weight: 1
    - identifier: aboutMe
      name: About me
      url: /about-me
      weight: 4
    - identifier: contactMe
      name: Contact me
      url: /contact-me
      weight: 5
    - identifier: hireMe
      name: Hire Me
      url: /hire-me
      weight: 3
    - identifier: search
      name: Search
      url: /search
      weight: 6




markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: monokai
    tabWidth: 4





languages:
  # English
  en:
    title: Omid Farhang
    languageName: ':us:'
    languageCode: en-US
    weight: 1
    params:
      profileMode:
        enabled: true
        imageUrl: "/images/bio-photo.jpg"
        subtitle: "I'm a Senior Developer and Also a network administrator, Working freelance and hunting for linux stuff"
    # English Menu
    menu:
      main:
        - name: Posts
          url: /posts
          weight: 1
        - name: About me
          url: /about-me
          weight: 4
        - name: Contact me
          url: /contact-me
          weight: 5
        - name: Hire Me
          url: /hire-me
          weight: 3
        - name: Search
          url: /search
          weight: 6
  # Persian
  fa:
    title: امید فرهنگ
    languageName: ':iran:'
    languageCode: fa-IR
    weight: 2
    languagedirection: rtl
    params:
      profileMode:
        enabled: true
        imageUrl: "/images/bio-photo.jpg"
        subtitle: "من یک برنامه‌نویس وب و مدیر شبکه هستم، به طور آزاد کار میکنم و به سیستم های لینوکسی علاقه دارم"
    # Persian Menu
    menu:
      main:
        - name: بلاگ
          url: /posts
          weight: 1
        - name: درباره من
          url: /about-me
          weight: 4
        - name: تماس با من
          url: /contact-me
          weight: 5
        - name: همکاری
          url: /hire-me
          weight: 3
        - name: جستجو
          url: /search
          weight: 6
  # Deutsch
  de:
    title: Omid Farhang
    languageName: ':de:'
    languageCode: de-DE
    weight: 2
    params:
      profileMode:
        enabled: true
        imageUrl: "/images/bio-photo.jpg"
        subtitle: "Ich bin Senior Developer und Netzwerkadministrator, arbeite freiberuflich und suche nach Linux-Sachen"
    # Deutsch Menu
    menu:
      main:
        - name: Posts
          url: /posts
          weight: 1
        - name: Über mich
          url: /about-me
          weight: 4
        - name: Kontaktiere mich
          url: /contact-me
          weight: 5
        - name: Stellt mich ein
          url: /hire-me
          weight: 3
        - name: Suche
          url: /search
          weight: 6


params:
  profileMode:
      enabled: true
      subtitle: "I'm a Senior Developer and Also a network administrator, Working freelance and hunting for linux stuff"
      imageUrl: "/images/bio-photo.jpg"

  assets:
  # Favicons
    favicon: /logo/favicon.ico
    favicon16x16: /logo/favicon-16x16.png
    favicon32x32: /logo/favicon-32x32.png
    apple_touch_icon: /logo/apple-touch-icon.png
    safari_pinned_tab: /logo/safari-pinned-tab.svg

  # Social Icons
  socialIcons:
  - name: linkedin
    url: 'https://linkedin.com/in/omidfarhang'
  - name: twitter
    url: 'https://twitter.com/omidfarhangen'
  - name: github
    url: 'https://github.com/omidfarhang'
  - name: mastodon
    url: 'https://mastodon.social/@omidfarhang'
  - name: instagram
    url: 'https://instagram.com/omidfarhang'
  - name: facebook
    url: 'https://facebook.com/omidfarhang'
  - name: telegram
    url: 'https://t.me/omidfarhang'
  - name: Rss
    url: "index.xml"
    linkedin: 'https://linkedin.com/in/omidfarhang'
    twitter: 'https://twitter.com/omidfarhangen'
    github: 'https://github.com/omidfarhang'
    mastodon: 'https://mastodon.social/@omidfarhang'
    instagram: 'https://instagram.com/omidfarhang'
    telegram: 'https://t.me/omidfarhang'

  mainSections:
    - posts

  displayFullLangName: true
  comments: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableScrollToTop: false
  showtoc: true
  tocopen: false

outputs:
    home:
        - HTML
        - RSS
        - JSON 
